<?php

/**
 * @file
 * Add content translation access permission.
 */

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;

/**
 * Implements hook_entity_field_access().
 */
function content_translation_access_user_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  if ($field_definition->getName() == 'field_access_languages') {
    // Check if permission for user is set for field_access_languages.
    if (!$account->hasPermission('edit local translation access')) {
      return AccessResult::forbidden();
    }
  }
  return AccessResult::neutral();
}
